# Generated by Django 4.2.6 on 2024-01-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0037_remove_board_backgroundimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="backgroundimage",
            field=models.ImageField(default="default_profile.png", upload_to="images/"),
        ),
    ]
