# Generated by Django 4.2.6 on 2024-01-29 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0039_remove_board_backgroundimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="invitation_link",
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
